from dataclasses import dataclass
from datetime import datetime
from typing import Any

RAG_SOURCE_ROLE = "user"


@dataclass(frozen=True, slots=True)
class ImageAttachment:
    """One image attached to a message, as a base64 data URL.

    ``data_url`` is the OpenAI-compatible ``data:image/jpeg;base64,...`` payload
    passed directly to vision models. ``telegram_file_id`` is kept for
    diagnostics / re-sending the photo later and is never sent to the model.
    ``description`` is an optional short text label (generated by the photo
    captioner) that makes a bare photo findable "by meaning" in RAG.
    """

    data_url: str
    mime_type: str = "image/jpeg"
    telegram_file_id: str | None = None
    description: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "data_url": self.data_url,
            "mime_type": self.mime_type,
            "telegram_file_id": self.telegram_file_id,
            "description": self.description,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ImageAttachment":
        return cls(
            data_url=str(data.get("data_url", "")),
            mime_type=str(data.get("mime_type") or "image/jpeg"),
            telegram_file_id=data.get("telegram_file_id"),
            description=data.get("description"),
        )


def attachments_to_dicts(attachments: tuple[ImageAttachment, ...]) -> list[dict[str, Any]]:
    return [attachment.to_dict() for attachment in attachments]


def attachments_from_dicts(data: list[dict[str, Any]] | None) -> tuple[ImageAttachment, ...]:
    if not data:
        return ()
    return tuple(ImageAttachment.from_dict(item) for item in data if isinstance(item, dict))


@dataclass(frozen=True, slots=True)
class ContextMessage:
    id: int
    role: str
    content: str
    sender_telegram_id: int | None = None
    sender_name: str | None = None
    created_at: datetime | None = None
    is_anchor: bool = False
    reply_to_message_id: int | None = None
    reply_to_text: str | None = None
    reply_to_sender_telegram_id: int | None = None
    reply_to_sender_name: str | None = None
    # Images attached to this message (vision turns / follow-up context).
    attachments: tuple[ImageAttachment, ...] = ()
    # Short generated label of the photo (photo_caption column) — lets a bare
    # photo be found "by meaning" in RAG and rendered in the photo album.
    photo_caption: str | None = None


@dataclass(frozen=True, slots=True)
class PhotoCandidate:
    """One photo the bot could re-send, listed for the compose model.

    ``index`` is the stable [photo:<index>] reference the model may emit; the
    bot re-sends the photo via ``telegram_file_id``. ``data_url`` carries the
    stored bytes (base64) so the bot can fall back to an upload when the
    Telegram file_id is stale or expired — a stale file_id must not silently
    turn a "sent" claim into a lost photo.
    """

    index: int
    telegram_file_id: str | None
    caption: str
    sender_name: str | None = None
    created_at: datetime | None = None
    data_url: str | None = None


@dataclass(frozen=True, slots=True)
class WebResult:
    """A single live web-search hit injected into the compose prompt.

    ``title`` / ``snippet`` are plain text (the providers return clean snippets,
    not HTML), ready to be rendered verbatim into the prompt. ``published_date``
    is optional — Tavily returns it when the page has one; it helps the model
    judge freshness (e.g. "how old is this news item"). Defined here (core) so
    the LLM provider protocol can reference it without importing the web-search
    service package (avoids a core -> services import cycle).
    """

    title: str
    url: str
    snippet: str
    # ISO date when the provider exposes one (e.g. Tavily's published_date).
    published_date: str | None = None


@dataclass(frozen=True, slots=True)
class ContextBlock:
    anchor_id: int
    messages: tuple[ContextMessage, ...]


@dataclass(frozen=True, slots=True)
class StoredMessage:
    id: int
    role: str
    content: str
    sender_telegram_id: int | None = None
    qdrant_point_id: str | None = None
    telegram_message_id: int | None = None
    sender_name: str | None = None
    created_at: datetime | None = None
    reply_to_message_id: int | None = None
    reply_to_text: str | None = None
    reply_to_sender_telegram_id: int | None = None
    reply_to_sender_name: str | None = None
    # Raw attachment dicts from the DB ``attachments`` JSONB column; None when
    # the row has none. Converted to ``ImageAttachment`` by ``stored_to_context``.
    attachments: list[dict[str, Any]] | None = None
    # Short generated label of the photo (photo_caption column), searchable by RAG.
    photo_caption: str | None = None


def stored_to_context(
    message: StoredMessage,
    *,
    is_anchor: bool = False,
) -> ContextMessage:
    return ContextMessage(
        id=message.id,
        role=message.role,
        content=message.content,
        sender_telegram_id=message.sender_telegram_id,
        sender_name=message.sender_name,
        created_at=message.created_at,
        is_anchor=is_anchor,
        reply_to_message_id=message.reply_to_message_id,
        reply_to_text=message.reply_to_text,
        reply_to_sender_telegram_id=message.reply_to_sender_telegram_id,
        reply_to_sender_name=message.reply_to_sender_name,
        attachments=attachments_from_dicts(message.attachments),
        photo_caption=message.photo_caption,
    )


def stored_block_to_context(
    anchor_id: int,
    messages: list[StoredMessage],
) -> ContextBlock | None:
    user_messages = [message for message in messages if message.role == RAG_SOURCE_ROLE]
    if not user_messages:
        return None
    anchor_id = next(
        (message.id for message in user_messages if message.id == anchor_id),
        user_messages[-1].id,
    )
    return ContextBlock(
        anchor_id=anchor_id,
        messages=tuple(
            stored_to_context(message, is_anchor=message.id == anchor_id)
            for message in user_messages
        ),
    )


def context_block_message_count(blocks: list[ContextBlock]) -> int:
    return sum(len(block.messages) for block in blocks)


def context_message_to_payload(message: ContextMessage) -> dict[str, Any]:
    created = message.created_at.isoformat() if message.created_at else None
    return {
        "id": message.id,
        "role": message.role,
        "content": message.content,
        "sender_telegram_id": message.sender_telegram_id,
        "sender_name": message.sender_name,
        "created_at": created,
    }


def context_message_from_payload(data: dict[str, Any]) -> ContextMessage:
    raw_created = data.get("created_at")
    created_at = None
    if isinstance(raw_created, str) and raw_created:
        created_at = datetime.fromisoformat(raw_created)
    return ContextMessage(
        id=int(data["id"]),
        role=str(data.get("role") or "user"),
        content=str(data.get("content") or ""),
        sender_telegram_id=data.get("sender_telegram_id"),
        sender_name=data.get("sender_name"),
        created_at=created_at,
    )
