apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: loki-config
    namespace: logging
    files:
      - local-config.yaml=loki-config.yaml
  - name: vector-config
    namespace: logging
    files:
      - vector.yaml=vector.yaml
resources:
  - 00-namespace.yaml
  - 20-loki.yaml
  - 21-vector.yaml
