apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../logging
patches:
  - path: bot-replicas.yaml
  - target:
      kind: StatefulSet
      name: loki
      namespace: logging
    path: loki-hostport.yaml
