#!/usr/bin/env bash
#
# Zero-downtime (blue-green) deploy for the Vanessa API behind Nginx.
#
# Implements the CI/CD flow:
#   1. Build a new image tagged with the version (default: short git SHA).
#   2. Start the new container (app_v2, the "green" one) on the shared Docker
#      network, on an internal port, connected to the same Postgres/Qdrant.
#   3. Wait until /health/ready of the new container returns 200 (it only does
#      once Postgres is reachable).
#   4. Point Nginx's upstream at the new container and `nginx -s reload`
#      (re-reads config without dropping active keepalive connections).
#   5. SIGTERM the old container (app_v1, "blue"), wait for it to stop
#      gracefully (uvicorn --timeout-graceful-shutdown drains in-flight
#      requests), then remove it.
#
# Usage:
#   scripts/zero_downtime_deploy.sh [VERSION]
#   VERSION defaults to "$(git rev-parse --short HEAD)".
#
# Prereqs: compose project `vanessaai` running with the nginx service, and the
# api service present on the default compose network. Run from repo root.

set -euo pipefail

VERSION="${1:-$(git rev-parse --short HEAD 2>/dev/null || echo dev)}"
IMAGE="vanessa-app:${VERSION}"

PROJECT="vanessaai"
NETWORK="${PROJECT}_default"
HEALTH_URL="http://localhost:8000/health/ready"
POLL_INTERVAL=2
POLL_MAX=60            # 120s max wait for readiness
GRACEFUL_TIMEOUT=30    # must match API_GRACEFUL_TIMEOUT in docker-compose.prod.yml

log() { echo "[deploy] $*"; }

# --- 1. Build the new image ------------------------------------------------
log "Building ${IMAGE}"
docker build -t "${IMAGE}" .

# --- Determine blue/green roles -------------------------------------------
# The currently running API container decides the colors. We manage two
# containers: api-blue and api-green. Whichever is running is "old"; the other
# becomes the new target.
GREEN=""
if docker inspect -f '{{.State.Running}}' "api-green" 2>/dev/null | grep -q true; then
    OLD="api-green"
    NEW="api-blue"
elif docker inspect -f '{{.State.Running}}' "api-blue" 2>/dev/null | grep -q true; then
    OLD="api-blue"
    NEW="api-green"
else
    # First deploy: no blue/green containers yet. Fall back to the compose
    # `api` service as the old one (it must be running on the network).
    log "No blue/green containers found; treating compose 'api' service as old"
    OLD="$(docker compose -p "${PROJECT}" ps -q api | head -n1)"
    NEW="api-blue"
fi
log "Deploying ${NEW} (${IMAGE}) next to ${OLD}"

# --- 2. Start the new container on the shared network ----------------------
# Internal port only (no host publish); Nginx reaches it via the Docker DNS
# name. Runs the same migration + uvicorn bootstrap as the compose api service.
log "Starting ${NEW} on ${NETWORK}"
docker rm -f "${NEW}" >/dev/null 2>&1 || true
docker run -d \
    --name "${NEW}" \
    --network "${NETWORK}" \
    --env-file .env \
    --health-cmd "curl -f ${HEALTH_URL} || exit 1" \
    --health-interval 5s --health-timeout 3s --health-retries 5 --health-start-period 30s \
    --stop-timeout "${GRACEFUL_TIMEOUT}" \
    "${IMAGE}" \
    sh -c "alembic upgrade head && \
           uvicorn app.api.main:app --host 0.0.0.0 --port 8000 \
           --timeout-graceful-shutdown ${GRACEFUL_TIMEOUT}"

# --- 3. Wait for readiness -------------------------------------------------
log "Waiting for ${NEW} readiness on /health/ready"
ready=0
for i in $(seq 1 "${POLL_MAX}"); do
    if curl -fsS "${HEALTH_URL}" >/dev/null 2>&1; then
        # /health/ready hits the load balancer; confirm the NEW container is
        # the one that is ready by checking its docker health status.
        if docker inspect -f '{{.State.Health.Status}}' "${NEW}" 2>/dev/null | grep -q healthy; then
            ready=1
            break
        fi
    fi
    sleep "${POLL_INTERVAL}"
done
if [ "${ready}" != "1" ]; then
    log "ERROR: ${NEW} never became ready; rolling back (keeping old upstream)"
    docker rm -f "${NEW}" >/dev/null 2>&1 || true
    exit 1
fi
log "${NEW} is healthy"

# --- 4. Point Nginx at the new container and reload ------------------------
log "Switching Nginx upstream to ${NEW}"
cat > deploy/nginx/conf.d/upstream.conf <<EOF
# Auto-generated by scripts/zero_downtime_deploy.sh — do not edit.
upstream vanessa_api {
    server ${NEW}:8000 max_fails=3 fail_timeout=30s;
    keepalive 32;
}
EOF
# Reload without dropping active keepalive connections.
docker compose -p "${PROJECT}" exec -T nginx nginx -s reload

# --- 5. Drain and remove the old container ----------------------------------
if [ -n "${OLD}" ] && [ "${OLD}" != "${NEW}" ]; then
    log "Sending SIGTERM to old container ${OLD}"
    docker kill --signal=SIGTERM "${OLD}"
    # Wait up to GRACEFUL_TIMEOUT + buffer for the in-flight requests to drain.
    for i in $(seq 1 "$((GRACEFUL_TIMEOUT + 15))"); do
        if ! docker inspect -f '{{.State.Running}}' "${OLD}" 2>/dev/null | grep -q true; then
            break
        fi
        sleep 1
    done
    log "Removing old container ${OLD}"
    docker rm -f "${OLD}" >/dev/null 2>&1 || true
fi

log "Deploy ${VERSION} complete. Active backend: ${NEW}"
